version: '3.1'

services:
  mongodbfluxocaixa:
    image: mongo:latest
    container_name: mongodbfluxocaixa
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: fluxocaixadb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 3000:8081
    links:
      - mongodbfluxocaixa
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      MONGO_INITDB_DATABASE: fluxocaixadb
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongodbfluxocaixa:27017
